# Generated by Django 3.2.7 on 2021-09-19 12:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_rename_stocks_stocks_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocks_model',
            name='age',
        ),
        migrations.RemoveField(
            model_name='stocks_model',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='stocks_model',
            name='last_name',
        ),
        migrations.AddField(
            model_name='stocks_model',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
